version: '3.7'

services:
    db:
      image: mysql:8
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=firestationquiz
      volumes:
        - db-data:/var/lib/mysql
      ports:
        - "3307:3306"
      restart: always
      networks:
        - game-data-network
    
    game-data-service:
        container_name: data-service
        build:
          dockerfile: Dockerfile
          context: .
        image: game-data-service:latest
        ports:
            - 8084:8084
        depends_on:
            - db
        environment:
          SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/firestationquiz?allowPublicKeyRetrieval=true&useSSL=false
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: root
        networks:
          - game-data-network

volumes:
  db-data: {}

networks:
  game-data-network:
    driver: bridge