version: '3.7'

services:
    game-data-service:
        container_name: data-service
        build:
          dockerfile: Dockerfile
          context: .
        image: game-data-service
        ports:
            - "8084:8084"
        networks:
          - game-data-network
        restart: always

networks:
  game-data-network:
    driver: bridge